### PR TITLE
Fix UG bugs

### LINKED ISSUE #166: [PE-D] Incorrect error message
G00 is not in class

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: bklimey/ped#2

### PR DESCRIPTION
**Pull request by nguyiyang**
Closes #166, #172, #175, #182

Updated and fixed bugs for tutorial group commands in UG.
Added some more testcases for tutorial groups.
Fixed empty class code bugs for commands using class code as a parameter.

### CODE REVIEW

File: src/main/java/seedu/address/model/tutorialgroup/GroupType.java [hunk 1]
```diff
@@ -24,10 +25,17 @@ public GroupType (String groupType) {
...
 
-    private Integer parseGroupType(String groupType) {
+    /**
+     * Gets the group type in terms of its number, 1 or 2.
+     *
+     * @param groupType The type of the group.
+     * @return The group type in terms of its number.
+     */
+    public static Integer parseGroupType(String groupType) {
+        assert groupType.length() == 3;
```
Comment (rushilramesh) [inline src/main/java/seedu/address/model/tutorialgroup/GroupType.java:38]: Good use of assertions

**Review by rushilramesh — APPROVED** [review]
LGTM!
